// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC27ce0hyS5L9h416-b5d4E9fRTMLpdDQk',
    appId: '1:525760575410:web:fa72dc69d4c8405fcad6ab',
    messagingSenderId: '525760575410',
    projectId: 'day-task-8e4c1',
    authDomain: 'day-task-8e4c1.firebaseapp.com',
    storageBucket: 'day-task-8e4c1.firebasestorage.app',
    measurementId: 'G-E1DNDPBWWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO9vZuGVconcVeopiR9Cu7QVkurQ23CRA',
    appId: '1:525760575410:android:70ad34da4c23c025cad6ab',
    messagingSenderId: '525760575410',
    projectId: 'day-task-8e4c1',
    storageBucket: 'day-task-8e4c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0iex5dMjPJaTaLvH8q_OMihzFtI1cgiA',
    appId: '1:525760575410:ios:5e905b8278d5b04ecad6ab',
    messagingSenderId: '525760575410',
    projectId: 'day-task-8e4c1',
    storageBucket: 'day-task-8e4c1.firebasestorage.app',
    iosBundleId: 'com.example.dayTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0iex5dMjPJaTaLvH8q_OMihzFtI1cgiA',
    appId: '1:525760575410:ios:5e905b8278d5b04ecad6ab',
    messagingSenderId: '525760575410',
    projectId: 'day-task-8e4c1',
    storageBucket: 'day-task-8e4c1.firebasestorage.app',
    iosBundleId: 'com.example.dayTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC27ce0hyS5L9h416-b5d4E9fRTMLpdDQk',
    appId: '1:525760575410:web:d06676736be5c582cad6ab',
    messagingSenderId: '525760575410',
    projectId: 'day-task-8e4c1',
    authDomain: 'day-task-8e4c1.firebaseapp.com',
    storageBucket: 'day-task-8e4c1.firebasestorage.app',
    measurementId: 'G-HLCRCBM1EC',
  );
}
